finding_aid_url_ssim: 'Finding Aid'
table_of_contents_tesim: 'Table of Contents'
summary_tesim: 'Summary'
note_publication_tesim: 'Publication Note'
note_publication_dates_tesim: 'Publication Dates'
holdings_note_tesim: 'Holdings Note'
language_ssim: 'Language'
note_language_tesim: 'Language Note'
note_accessibility_tesim: 'Accessibility Note'
material_type_display_tesim: 'Physical Type/Description'
note_technical_tesim: 'Technical Note'
note_access_restriction_tesim: 'Restrictions on Access'
note_use_tesim: 'Use and Reproduction'
note_general_tsim: 'General Note'
note_local_tesim: 'Local Note'
note_bound_with_tesim: 'Bound With'
note_preferred_citation_tesim: 'Preferred Citation'
note_awards_tesim: 'Awards'
note_bibliography_tesim: 'Bibliography'
note_acquisition_tesim: 'Source of Acquisition'
note_participant_tesim: 'Participant/Performer Note'
note_production_tesim: 'Creation/Production Credits Note'
note_time_place_event_tesim: 'Date/Time and Place of an Event'
note_arrangement_tesim: 'Organization and Arrangement'
note_addl_form_tesim: 'Additional Physical Form'
note_historical_tesim: 'Biographical/Historical Note'
note_reproduction_tesim: 'Reproduction Note'
note_location_originals_tesim: 'Location of Originals'
note_custodial_tesim: 'Ownership and Custodial History'
note_copy_identification_tesim: 'Copy and Version Identification'
note_binding_tesim: 'Binding Note'
note_citation_tesim: 'Citation/Reference Note'
note_related_collections_tesim: 'Related Collections'
url_suppl_ssim: 'Related Resources Link'