"gender identity disorder":
  replacement: "Gender dysphoria"
  rationale: "https://docs.google.com/spreadsheets/d/1uqiP5PPKXJt35uFLrG5ytsLbz2kgWXBjG__hyD12KlY/edit?gid=0#gid=0"
"gender identity disorders":
  replacement: "Gender dysphoria"
"gender identity disorders in children":
  replacement: "Gender dysphoria in children"
"gender identity disorders in adolescence":
  replacement: "Gender dysphoria in adolescence"
"african american gays in literature":
  replacement: "African American gay people in literature"
"african american gays":
  replacement: "African American gay people"
"african american sexual minorities":
  replacement: "african american sexual minorities"
"african american sexual minority students":
  replacement: "African American LGBTQ+ students"
"african american sexual minority youth":
  replacement: "African American LGBTQ+ youth"
"alien criminals":
  replacement: "Noncitizen criminals"
"alien detention centers":
  replacement: "Noncitizen detention centers"
"alien labor":
  replacement: "Foreign workers"
"alien property":
  replacement: "Foreign property"
"aliens":
  replacement: "Noncitizens"
"arab american sexual minorities":
  replacement: "Arab American LGBTQ+ people"
"artificial satellites, east indian":
  replacement: "Artificial satellites, Indian (India)"
"asian american gays":
  replacement: "Asian American gay people"
"asian american sexual minorities":
  replacement: "Asian American LGBTQ+ people"
"asian american sexual minority students":
  replacement: "Asian American LGBTQ+ students"
"asian american sexual minority youth":
  replacement: "Asian American LGBTQ+ youth"
"banks and banking, east indian":
  replacement: "Banks and banking, Indian (India)"
"catholic gays":
  replacement: "Catholic gay people"
"catholic sexual minorities":
  replacement: "Catholic LGBTQ+ people"
"child slaves":
  replacement: "Enslaved children"
"children of illegal aliens":
  replacement: "Children of noncitizens"
"children of sexual minority parents":
  replacement: "Children of LGBTQ+ parents"
"christian gays":
  replacement: "Christian gay people"
"christian sexual minorities":
  replacement: "Christian LGBTQ+ people"
"church work with african american gays":
  replacement: "Church work with African American gay people"
"church work with ex-convicts":
  replacement: "Church work with formerly incarcerated persons"
"church work with gays":
  replacement: "Church work with gay people"
"church work with sexual minorities":
  replacement: "Church work with LGBTQ+ people"
"church work with sexual minority youth":
  replacement: "Church work with LGBTQ+ youth"
"civics, east indian":
  replacement: "Civics, Indian (India)"
"closeted gays":
  replacement: "Closeted gay people"
"corporations, east indian":
  replacement: "Corporations, Indian (India)"
"deaf gays":
  replacement: "Deaf gay people"
"diplomatic and consular service, east indian":
  replacement: "Diplomatic and consular service, Indian (India)"
"east indian american business enterprises":
  replacement: "Indian American business enterprises"
"east indian american businesspeople":
  replacement: "Indian American businesspeople"
"east indian american college students":
  replacement: "Indian American college students"
"east indian american physicians":
  replacement: "Indian American physicians"
"east indian american teenagers":
  replacement: "Indian American teenagers"
"east indian american women":
  replacement: "Indian American women"
"east indian americans in literature":
  replacement: "Indian Americans in literature"
"east indian americans":
  replacement: "Indian Americans"
"east indian authors":
  replacement: "Indian authors (India)"
"east indian autonomous regions":
  replacement: "Indian autonomous regions (India)"
"east indian business enterprises":
  replacement: "Indian business enterprises (India)"
"east indian diaspora in art":
  replacement: "Indian diaspora in art (India)"
"east indian diaspora in literature":
  replacement: "Indian diaspora in literature (India)"
"east indian diaspora in motion pictures":
  replacement: "Indian diaspora in motion pictures (India)"
"east indian diaspora":
  replacement: "Indian diaspora (India)"
"east indian students":
  replacement: "Indian students (India)"
"east indians in art":
  replacement: "Indians in art (India)"
"east indians in literature":
  replacement: "Indians in literature (India)"
"east indians in motion pictures":
  replacement: "Indians in motion pictures (India)"
"east indians":
  replacement: "Indians (India)"
"economic assistance, east indian":
  replacement: "Economic assistance, Indian (India)"
"espionage, east indian":
  replacement: "Espionage, Indian (India)"
"ex-convicts":
  replacement: "Formerly incarcerated persons"
"foreign workers, east indian":
  replacement: "Foreign workers, Indian (India)"
"freedmen":
  replacement: "Freed persons."
"fugitive slaves":
  replacement: "Fugitive enslaved persons"
"gays and rock music":
  replacement: "Gay people and rock music"
"gays and sports":
  replacement: "Gay people and sports"
"gays and the performing arts":
  replacement: "Gay people and the performing arts"
"gays in higher education":
  replacement: "Gay people in higher education"
"gays in literature":
  replacement: "Gay people in literature"
"gays in motion pictures":
  replacement: "Gay people in motion pictures"
"gays in popular culture":
  replacement: "Gay people in popular culture"
"gays in the performing arts":
  replacement: "Gay people in the performing arts"
"gays":
  replacement: "Gay people"
"gays' writings, american":
  replacement: "Gay peoples' writings, American"
"gays' writings, australian":
  replacement: "Gay peoples' writings, Australian"
"gays' writings, austrian":
  replacement: "Gay peoples' writings, Austrian"
"gays' writings, basque":
  replacement: "Gay peoples' writings, Basque"
"gays' writings, canadian":
  replacement: "Gay peoples' writings, Canadian"
"gays' writings, catalan":
  replacement: "Gay peoples' writings, Catalan"
"gays' writings, chilean":
  replacement: "Gay peoples' writings, Chilean"
"Gays' writings, chinese":
  replacement: "Gay peoples' writings, Chinese"
"gays' writings, dominican":
  replacement: "Gay peoples' writings, Dominican"
"gays' writings, english":
  replacement: "Gay peoples' writings, English"
"gays' writings, french":
  replacement: "Gay peoples' writings, French"
"gays' writings, galician":
  replacement: "Gay peoples' writings, Galician"
"gays' writings, german":
  replacement: "Gay peoples' writings, German"
"gays' writings, irish":
  replacement: "Gay peoples' writings, Irish"
"gays' writings, israeli":
  replacement: "Gay peoples' writings, Israeli"
"gays' writings, italian":
  replacement: "Gay peoples' writings, Italian"
"gays' writings, latin american":
  replacement: "Gay peoples' writings, Latin American"
"gays' writings, philippine (english)":
  replacement: "Gay peoples' writings, Philippine (English)"
"gays' writings, portuguese":
  replacement: "Gay peoples' writings, Portuguese"
"gays' writings, south african (english)":
  replacement: "Gay peoples' writings, South African (English)"
"gays' writings, spanish american":
  replacement: "Gay peoples' writings, Spanish American"
"gays' writings, spanish":
  replacement: "Gay peoples' writings, Spanish"
"gays' writings, tagalog":
  replacement: "Gay peoples' writings, Tagalog"
"hearing impaired":
  replacement: "Hard of hearing people"
"hearing impaired children":
  replacement: "Hard of hearing children"
"hispanic american gays":
  replacement: "Hispanic American gay people"
"hispanic american sexual minorities":
  replacement: "Hispanic American LGBTQ+ people"
"hispanic american sexual minority students":
  replacement: "Hispanic American LGBTQ+ students"
"hispanic american sexual minority youth":
  replacement: "Hispanic American LGBTQ+ youth"
"humanitarian assistance, east indian":
  replacement: "Humanitarian assistance, Indian (India)"
"illegal alien children":
  replacement: "Noncitizen children"
"illegal aliens in literature":
  replacement: "Noncitizens in literature"
"illegal aliens":
  replacement: "Unauthorized immigration"
"illegal immigration":
  replacement: "Unauthorized immigration"
"indian sexual minorities":
  replacement: "Indigenous LGBTQ+ people"
"indian sexual minority students":
  replacement: "Indigenous LGBTQ+ students"
"indian sexual minority youth":
  replacement: "Indigenous LGBTQ+ youth"
"indian slaves":
  replacement: "Enslaved indigenous peoples"
"Enslaved Indians":
  replacement: "Enslaved indigenous peoples"
"investments, east indian":
  replacement: "Investments, Indian (India)"
"italian american gays":
  replacement: "Italian American gay people"
"jewish gays":
  replacement: "Jewish gay people"
"jewish sexual minorities":
  replacement: "Jewish LGBTQ+ people"
"jews, east indian":
  replacement: "Jews, Indian (India)"
"legal assistance to gays":
  replacement: "Legal assistance to gay people"
"libraries and gays":
  replacement: "Libraries and gay people"
"libraries and sexual minorities":
  replacement: "Libraries and LGBTQ+ people"
"mass media and gays":
  replacement: "Mass media and gay people"
"mexican american gays":
  replacement: "Mexican American gay people"
"middle-aged gays":
  replacement: "Middle-aged gay people"
"middle-aged sexual minorities":
  replacement: "Middle-aged LGBTQ+ people"
"minority gays":
  replacement: "Minority gay people"
"mormon gays":
  replacement: "Mormon gay people"
"museums and sexual minorities":
  replacement: "Museums and LGBTQ+ people"
"national characteristics, east indian, in literature":
  replacement: "National characteristics, Indian, in literature (India)"
"national characteristics, east indian":
  replacement: "National characteristics, Indian (India)"
"occupational training for ex-convicts":
  replacement: "Occupational training for formerly incarcerated persons"
"older gays":
  replacement: "Older gay people"
"older sexual minorities":
  replacement: "Older LGBTQ+ people"
"older sexual minority women":
  replacement: "Older LGBTQ+ women"
"older slaves":
  replacement: "Enslaved older people"
"ordination of gays":
  replacement: "Ordination of gay people"
"pacific islander american sexual minorities":
  replacement: "Pacific Islander American LGBTQ+ people"
"pacific islander american sexual minority students":
  replacement: "Pacific Islander American LGBTQ+ students"
"pacific islander american sexual minority youth":
  replacement: "Pacific Islander American LGBTQ+ youth"
"pacific lslander american gays":
  replacement: "Pacific Islander American gay people"
"parents of gays":
  replacement: "Parents of gay people"
"parents of sexual minority youth":
  replacement: "Parents of LGBTQ+ youth"
"peacekeeping forces, east indian":
  replacement: "Peacekeeping forces, Indian (India)"
"personal narratives, east indian":
  replacement: "Personal narratives, Indian (India)"
"police services for sexual minorities":
  replacement: "Police services for LGBTQ+ people"
"poor":
  replacement: "Poor people"
"prison riots":
  replacement: "Prison uprisings"
"radio programs for gays":
  replacement: "Radio programs for gay people"
"refugee property, east indian":
  replacement: "Refugee property, Indian (India)"
"relations with east indians":
  replacement: "Relations with Indians (India)"
"rural sexual minorities":
  replacement: "Rural LGBTQ+ people"
"sexual minorities (islamic law)":
  replacement: "LGBTQ+ people (Islamic law)"
"sexual minorities in advertising":
  replacement: "LGBTQ+ people in advertising"
"sexual minorities in art":
  replacement: "LGBTQ+ people in art"
"sexual minorities in education":
  replacement: "LGBTQ+ people in education"
"sexual minorities in higher education":
  replacement: "LGBTQ+ people in higher education"
"sexual minorities in literature":
  replacement: "LGBTQ+ people in literature"
"sexual minorities in mass media":
  replacement: "LGBTQ+ people in mass media"
"sexual minorities in motion pictures":
  replacement: "LGBTQ+ people in motion pictures"
"sexual minorities on television":
  replacement: "LGBTQ+ people on television"
"sexual minorities with disabilities":
  replacement: "LGBTQ+ people with disabilities"
"sexual minorities, romani":
  replacement: "LGBTQ+ people, Romani"
"sexual minorities":
  replacement: "LGBTQ+ people"
"sexual minorities' families":
  replacement: "LGBTQ+ people's families"
"sexual minorities' writings, american":
  replacement: "LGBTQ+ people's writings, American"
"sexual minorities' writings, australian":
  replacement: "LGBTQ+ people's writings, Australian"
"sexual minorities' writings, brazilian":
  replacement: "LGBTQ+ people's writings, Brazilian"
"sexual minorities' writings, canadian":
  replacement: "LGBTQ+ people's writings, Canadian"
"sexual minorities' writings, chinese":
  replacement: "LGBTQ+ people's writings, Chinese"
"sexual minorities' writings, english":
  replacement: "LGBTQ+ people's writings, English"
"sexual minorities' writings, malaysian (english)":
  replacement: "LGBTQ+ people's writings, Malaysian (English)"
"sexual minorities' writings":
  replacement: "LGBTQ+ people's writings"
"sexual minority business enterprises":
  replacement: "LGBTQ+ business enterprises"
"sexual minority college athletes":
  replacement: "LGBTQ+ college athletes"
"sexual minority college students":
  replacement: "LGBTQ+ college students"
"sexual minority community":
  replacement: "LGBTQ+ community"
"sexual minority consumers":
  replacement: "LGBTQ+ consumers"
"sexual minority culture":
  replacement: "LGBTQ+ culture"
"sexual minority immigrants":
  replacement: "LGBTQ+ immigrants"
"sexual minority legislators":
  replacement: "LGBTQ+ legislators"
"sexual minority men":
  replacement: "LGBTQ+ men"
"sexual minority military personnel":
  replacement: "LGBTQ+ military personnel"
"sexual minority parents":
  replacement: "LGBTQ+ parents"
"sexual minority political candidates":
  replacement: "LGBTQ+ political candidates"
"sexual minority political refugees":
  replacement: "LGBTQ+ political refugees"
"sexual minority politicians":
  replacement: "LGBTQ+ politicians"
"sexual minority public officers":
  replacement: "LGBTQ+ public officers"
"sexual minority religious leaders":
  replacement: "LGBTQ+ religious leaders"
"sexual minority students":
  replacement: "LGBTQ+ students"
"sexual minority teachers":
  replacement: "LGBTQ+ teachers"
"sexual minority veterans":
  replacement: "LGBTQ+ veterans"
"sexual minority women":
  replacement: "LGBTQ+ women"
"sexual minority youth in mass media":
  replacement: "LGBTQ+ youth in mass media"
"sexual minority youth with disabilities":
  replacement: "LGBTQ+ youth with disabilities"
"sexual minority youth":
  replacement: "LGBTQ+ youth"
"slave insurrections in literature":
  replacement: "Slave rebellions in literature"
"slave insurrections":
  replacement: "Slave rebellions "
"slave owners":
  replacement: "Enslavers"
"Slaveholders":
  replacement: "Enslavers"
"slaves":
  replacement: "Enslaved persons"
"social work with gays":
  replacement: "Social work with gay people"
"social work with older sexual minorities":
  replacement: "Social work with older LGBTQ+ people"
"social work with sexual minorities":
  replacement: "Social work with LGBTQ+ people"
"social work with sexual minority youth":
  replacement: "Social work with LGBTQ+ youth"
"south asian american gays":
  replacement: "South Asian American gay people"
"television programs for gays":
  replacement: "Television programs for gay people"
"unitarian Universalist sexual minorities":
  replacement: "Unitarian Universalist LGBTQ+ people"
"web sites for sexual minorities":
  replacement: "Web sites for LGBTQ+ people"
"women ex-convicts":
  replacement: "Formerly incarcerated women"
"women illegal aliens":
  replacement: "Women noncitizens"
"women slaves":
  replacement: "Enslaved women"
"women, east indian":
  replacement: "Women, Indian (India)"