"Gender identity disorder":
  replacement: "Gender dysphoria"
"Gender identity disorders":
  replacement: "Gender dysphoria"
"Gender identity disorders in children":
  replacement: "Gender dysphoria in children"
"Gender identity disorders in adolescence":
  replacement: "Gender dysphoria in adolescence"
"Indians of North America":
  replacement: "Indigenous peoples of North America"
"Indians of South America":
  replacement: "Indigenous peoples of South America"